"""Generate synthetic SFT pairs from the corpus RAG records.

Reads already-routed RAG JSONL (data/corpus/rag/**/*.jsonl), runs each record
through app.corpus.sft_synth, and writes chat-format SFT lines. Idempotent: a
content-hash state file means re-runs only process new records.

LICENSE NOTE: with SFT_INCLUDE_RESTRICTED on (default), this derives SFT from
Apple-licensed docs too. The output is for PERSONAL / LOCAL fine-tuning only,
NOT redistribution. Every record carries its true license_bucket + sft_origin.
"""
from __future__ import annotations

import argparse
import asyncio
import json
import os
from pathlib import Path
from typing import Any, Dict, Iterator

import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.corpus import sft_synth

_PROVENANCE_TEXT = (
    "# Synthetic SFT — provenance\n\n"
    "These pairs were generated by scripts/generate_sft.py from scraped corpus\n"
    "records. When SFT_INCLUDE_RESTRICTED is on, pairs are derived from\n"
    "Apple-licensed documentation as well. **Personal / local fine-tuning use\n"
    "only — not for redistribution.** Each record carries its true\n"
    "`license_bucket` and `sft_origin: synthetic`.\n"
)


def to_sft_record(record: Dict[str, Any], pair: Dict[str, str]) -> Dict[str, Any]:
    return {
        "type": pair.get("kind", "conceptual"),
        "framework": record.get("framework", ""),
        "source_url": record.get("url", ""),
        "license_bucket": record.get("license_bucket", "unknown"),
        "sft_origin": "synthetic",
        "swift_version": record.get("swift_version", ""),
        "messages": [
            {"role": "user", "content": pair["question"]},
            {"role": "assistant", "content": pair["answer"]},
        ],
    }


def iter_rag_records(rag_dir) -> Iterator[Dict[str, Any]]:
    for path in sorted(Path(rag_dir).rglob("*.jsonl")):
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line:
                yield json.loads(line)


def eligible(record: Dict[str, Any], include_restricted: bool) -> bool:
    if include_restricted:
        return True
    return not str(record.get("license_bucket", "")).startswith("apple-")


def _load_state(state_path) -> set:
    p = Path(state_path)
    if not p.exists():
        return set()
    return set(json.loads(p.read_text(encoding="utf-8")).get("seen_hashes", []))


def _save_state(state_path, seen: set) -> None:
    Path(state_path).parent.mkdir(parents=True, exist_ok=True)
    Path(state_path).write_text(
        json.dumps({"seen_hashes": sorted(seen)}, ensure_ascii=False), encoding="utf-8")


async def run(rag_dir, out_dir, *, include_restricted: bool, n: int, limit: int,
              state_path, extractor=None) -> Dict[str, int]:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "_PROVENANCE.md").write_text(_PROVENANCE_TEXT, encoding="utf-8")
    seen = _load_state(state_path)

    stats = {"records": 0, "pairs": 0, "skipped_seen": 0, "skipped_restricted": 0, "llm_skipped": 0}
    out_file = out_dir / "synthetic-sft.jsonl"
    with open(out_file, "a", encoding="utf-8") as fh:
        for record in iter_rag_records(rag_dir):
            h = record.get("content_hash") or record.get("url")
            if h in seen:
                stats["skipped_seen"] += 1
                continue
            if not eligible(record, include_restricted):
                stats["skipped_restricted"] += 1
                continue
            result = await sft_synth.generate_pairs(record, n=n, extractor=extractor)
            if result.get("llm_skipped"):
                stats["llm_skipped"] += 1
            for pair in result["pairs"]:
                fh.write(json.dumps(to_sft_record(record, pair), ensure_ascii=False) + "\n")
                stats["pairs"] += 1
            seen.add(h)
            stats["records"] += 1
            if limit and stats["records"] >= limit:
                break
    _save_state(state_path, seen)
    return stats


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    base = os.environ.get("DATA_DIR", os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data"))
    ap.add_argument("--rag-dir", default=os.path.join(base, "corpus", "rag"))
    ap.add_argument("--out-dir", default=os.path.join(base, "corpus", "sft"))
    ap.add_argument("--state", default=os.path.join(base, "corpus", ".sft_state.json"))
    ap.add_argument("--pairs", type=int, default=2, help="conceptual pairs per record")
    ap.add_argument("--limit", type=int, default=0, help="cap records (0 = all)")
    include_restricted = os.environ.get("SFT_INCLUDE_RESTRICTED", "true").lower() != "false"
    ap.add_argument("--permissive-only", dest="include_restricted", action="store_false",
                    default=include_restricted, help="skip apple-* buckets (override the env default)")
    args = ap.parse_args()

    stats = asyncio.run(run(args.rag_dir, args.out_dir,
                            include_restricted=args.include_restricted, n=args.pairs,
                            limit=args.limit, state_path=args.state))
    print(f"SFT generation: {stats}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
